17 Trying to fix issue with Terraform not running

diff --git a/bin/set_tf_alias b/bin/set_tf_alias
--- a/bin/set_tf_alias
+++ b/bin/set_tf_alias
@@ -1,16 +1,17 @@
 #!/usr/bin/env bash
 
 # Check if the alias already exists in the .bash_profile
-grep -q 'alias tf="terraform" ~/.bash_profile'
+grep -q 'alias tf="terraform"' ~/.bash_profile
 
-# $? is a special variable in bash that golds the exit status of the 
+# $? is a special variable in bash that holds the exit status of the last command executed
 if [ $? -ne 0 ]; then
     # If the alias does not exist, append it
-    echo 'Alias tf="terraform"' >> ~/.bash_profile
+    echo 'alias tf="terraform"' >> ~/.bash_profile
     echo "Alias added successfully."
 else
     # Inform the user if the alias already exists
-    echo "Alias 'tf' already exists in ~/.bash_profile."
-fi 
+    echo "Alias already exists in .bash_profile."
+fi
 
-source ./bin/set_tf_alias
+# Optional: source the .bash_profile to make the alias available immediately
+source ~/.bash_profile
